// Central messaging constants

export const MSG_TYPES = {
  // Page info
  GET_PAGE_INFO: 'GET_PAGE_INFO',
  PAGE_INFO_RESPONSE: 'PAGE_INFO_RESPONSE',
  
  // Selection
  GET_SELECTION: 'GET_SELECTION',
  SELECTION_CHANGED: 'SELECTION_CHANGED',
  
  // Actions
  SUMMARIZE_PAGE: 'SUMMARIZE_PAGE',
  EXPLAIN_SELECTION: 'EXPLAIN_SELECTION',
  TRANSLATE: 'TRANSLATE',
  SAVE_WORKSPACE: 'SAVE_WORKSPACE',
  ASK_NEUROLENS: 'ASK_NEUROLENS',
  
  // System
  TOGGLE_SIDEPANEL: 'TOGGLE_SIDEPANEL',
  STATUS_UPDATE: 'STATUS_UPDATE',
  ERROR: 'ERROR'
};

export const ERROR_CODES = {
  TIMEOUT: 'TIMEOUT',
  NO_TAB: 'NO_TAB',
  INVALID_MESSAGE: 'INVALID_MESSAGE'
};
